"""Initial migration for users and todos tables

Revision ID: 615367339a09
Revises: 
Create Date: 2026-01-10 16:48:14.900419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '615367339a09'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the users table with role as string column first
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),  # Use string initially
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)

    # Create the todos table
    op.create_table('todos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todos_user_id'), 'todos', ['user_id'], unique=False)

    # Now alter the role column to use the enum type
    # Check if enum exists first
    conn = op.get_bind()
    result = conn.execute(sa.text("""
        SELECT 1 FROM pg_type WHERE typname = 'userrole';
    """))

    if not result.fetchone():
        # Create the enum type
        op.execute("CREATE TYPE userrole AS ENUM ('admin', 'user');")

    # Alter the column to use the enum type
    op.alter_column('users', 'role', type_=sa.Enum('admin', 'user', name='userrole'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Change role column back to string before dropping tables
    op.alter_column('users', 'role', type_=sa.String())

    # Drop the enum type if it exists
    conn = op.get_bind()
    result = conn.execute(sa.text("""
        SELECT 1 FROM pg_type WHERE typname = 'userrole';
    """))

    if result.fetchone():
        op.execute("DROP TYPE userrole;")

    op.drop_index(op.f('ix_todos_user_id'), table_name='todos')
    op.drop_table('todos')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
